#Buildfile to instruct Travis how to build this project.
language:
  javascript
install:
  - npm install
  - bower install

script:
  ls  #placeholder to prevent travis running ant build?

after_success:
  - test $TRAVIS_BRANCH == "master" && bash deploy.sh #Deploy to github gh-pages using the deploy.sh file

## IMPORTANT NOTE: for this deploy script to do anything, ensure there is an
# environment variable called GH_TOKEN set up for the build. The token comes from
# Github here: https://github.com/settings/tokens/new & needs 'repo' premissions.
